# Config file for training capsules

trainer:
  file: trainer_main
  type: "TrainerMultiFrame"
  max_epochs: 300
  regularizer: 
    layer: "kernel_regularizer"
    type: "L1"
    weight: 0.001
  optimizer: 
    type: Adam
    args:
      lr: 6e-4
  scheduler:
    steps: [100, 200, 250]  
    decay_rate: 1e-1
  monitor:
    metric: "val_l2_loss"
  seed: 1234

features:
  rotation:
    use: true
  partiality:
    use: false

model:
  file: tfn_capsules_multi_frame
  type: "TFN_multi"
  args:
    num_classes: 1024
    num_frames: 5
    num_capsules: 10
  weights: false

loss:
  l2_loss: 2.0
  eq_loss: 1.0
  loc_loss: 0.1
  caps_chamf_loss: 0.3
  orth_loss: 1.0
  caps_partiality_loss: 1.0
  directional_loss_partial: 0.4
  capsule_position_loss: 0.4
  caps_spatial_loss: 0.1
  inv_partiality_loss: 1.0
  chamfer_loss: 1.0
  hausdorff_loss: 0.0
  loss_shape_svd: 0.4
  separation_loss_basis: 0.4


dataset:
  path: "../dataset/ShapeNetAtlasNetH5_1024"
  batch_size: 16
  shuffle: True
  num_points: 1024
  val_list: ["val_plane.h5"]
  train_list: ["train_plane.h5"]
  test_list: ["val_plane.h5"]

# dataset:
#   path: "/scratch/rahulsajnani/research/brown/test_final/EquiNet/NOCS-dataset-generator/src/"
#   batch_size: 16
#   shuffle: True
#   num_points: 1024
#   val_list: [cars_nocs_val.h5]
#   train_list: [cars_nocs_train.h5]
#   test_list: [cars_nocs_test.h5]

test:
  max_iter: 200
  
save:
  path: "./checkpoints"
utils:
  eps: 1e-8
