
method: CaDeX-ATC-door-dep
gpu: 0,1
modes: ["train", "val"]

model:
  model_name: cadex_s2m

  loss_recon: true
  loss_corr: true
  corr_weight: 8.0
  corr_square: true

  compress_cdc: true # the cdc is compressed by a sigmoid

  homeomorphism_encoder:
    c_dim: 256
    hidden_dim: 256
    ci_dim: 256
  ci_decoder:
    ci_dim: 256
    c_dim: 256
    amp_dim: 256
    hidden_dim: 256
  canonical_geometry_encoder:
    c_dim: 256
    hidden_dim: 256
  canonical_geometry_decoder:
    c_dim: 256
    hidden_size: 256
  homeomorphism_decoder:
    n_layers: 3
    feature_dims: 256
    hidden_size: [256, 128, 64, 64, 32, 32]
    proj_dims: 256
    code_proj_hidden_size: [256, 256, 256]
    proj_type: simple
    block_normalize: False
    normalization: False # coupling block
    explicit_affine: False
    # hardtanh_range: [-3.0, 3.0] #default 10.0

dataset:
  pin_mem: False
  dataset_name: shape2motion
  data_root: ./resource/data/s2m/door
  dataset_proportion: [1.0, 1.0] #  [0.1, 0.1]
  num_workers: 10

  num_atc: 1

  occ_n_chunk: 10
  corr_n_chunk: 10
  chunk_size: 10000

  # customized setting
  input_type: "dep"

  split:
    train: train.json
    val: val.json
    test: test.json

  set_size: 8
  input_num: 4

  pcl_traj: false
  camera_frame: false

  num_input_pts: 300
  input_noise: 0.003
  num_query_uni: 1024
  num_query_ns: 1024
  num_corr_pts: 256
  n_query_sample_eval: 10000 # this is for val, for testing set to 100000

training:
  grad_clip: 4.0
  loss_clip: 4.0
  optim:
    all:
      lr: 0.0001
      decay_schedule: [50, 70, 80, 90]
      decay_factor: [0.3, 0.3, 0.3, 0.3]
      lr_min: 0.00000001

  total_epoch: 101
  batch_size: 6

evaluation:
  eval_every_epoch: 3
  iou_threshold: 0.5
  batch_size: 4
  project_to_final_mesh: false

logging:
  log_dir: cadex_s2m_door_dep
  loggers: ["mesh", "image", "hist", "video", "xls"]
  viz_training_batch_interval: 40
  viz_nontrain_batch_interval: 10
  viz_epoch_interval: 3
  checkpoint_epoch: 25
  mesh_viz_interval: 1

  model_select_metric: iou
  model_select_larger: true

  viz_align_cdc: false

generation:
  occ_if_meshing_cfg:
    threshold: 0.5
    batch_pts: 8000
    simplify_nfaces: 5000
        
        